# Generated by Django 3.2.3 on 2021-06-13 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='recipient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='profile.profile'),
            preserve_default=False,
        ),
    ]
