# Generated by Django 3.2.3 on 2021-10-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('a', 'accepted'), ('d', 'declined'), ('p', 'in process'), ('m', 'on moderation')], default='a', max_length=20),
        ),
    ]
