# Generated by Django 3.2.3 on 2021-09-17 22:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('storages', '0019_storage_promo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=254, null=True, verbose_name='email address')),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 16 digits allowed.", regex='^\\+?\\d{9,16}$')])),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('a', 'accepted'), ('d', 'declined'), ('m', 'on moderation')], default='m', max_length=1)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='storages.storage')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
