# Generated by Django 3.2.3 on 2021-09-23 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0020_alter_storage_status'),
        ('feedback', '0002_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagefeedback',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='storages.storage'),
        ),
    ]
