# Generated by Django 3.2.3 on 2021-10-11 19:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0020_alter_storage_status'),
        ('feedback', '0003_alter_storagefeedback_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 16 digits allowed.", regex='^\\+?\\d{9,16}$')])),
                ('email', models.EmailField(db_index=True, max_length=254, null=True, verbose_name='email address')),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='storagefeedback',
            name='storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_set', to='storages.storage'),
        ),
    ]
