# Generated by Django 3.2.3 on 2021-10-11 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20211011_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagefeedback',
            name='status',
            field=models.CharField(choices=[('a', 'accepted'), ('d', 'declined'), ('m', 'on moderation')], default='a', max_length=1),
        ),
    ]
