# Generated by Django 3.2.3 on 2021-06-18 11:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('square', models.FloatField(blank=True, max_length=20, null=True)),
                ('price', models.FloatField(blank=True, max_length=20, null=True)),
                ('access', models.CharField(choices=[('24h', 'around clock'), ('ttt', 'from time to time')], default='ttt', max_length=30)),
                ('work_hours_start', models.TimeField(default='00:00:00')),
                ('work_hours_end', models.TimeField(default='23:59:59')),
                ('surveillance', models.CharField(choices=[('v', 'video'), ('h', 'human'), ('n', 'none')], default='n', max_length=10)),
                ('climate', models.CharField(choices=[('c', 'cold'), ('w', 'warm')], default='w', max_length=4)),
                ('album', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='images.imagealbum')),
                ('company_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
