# Generated by Django 3.2.3 on 2021-06-12 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('company', '0002_company_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('square', models.CharField(blank=True, max_length=20, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('access', models.CharField(blank=True, choices=[('24h', 'around clock'), ('ttt', 'from time to time')], max_length=30, null=True)),
                ('work_hours_start', models.TimeField(blank=True, null=True)),
                ('work_hours_end', models.TimeField(blank=True, null=True)),
                ('surveillance', models.CharField(blank=True, choices=[('v', 'video'), ('h', 'human'), ('n', 'none')], max_length=10, null=True)),
                ('climate', models.CharField(blank=True, choices=[('c', 'cold'), ('w', 'warm')], max_length=4, null=True)),
                ('album', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='images.imagealbum')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
