# Generated by Django 3.2.3 on 2021-05-27 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('square', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('access', models.CharField(choices=[('24h', 'around clock'), ('ttt', 'from time to time')], max_length=30)),
                ('work_hours_start', models.TimeField(blank=True, null=True)),
                ('work_hours_end', models.TimeField(blank=True, null=True)),
                ('surveillance', models.CharField(choices=[('v', 'video'), ('h', 'human'), ('n', 'none')], max_length=10)),
                ('climate', models.CharField(choices=[('c', 'cold'), ('w', 'warm')], max_length=4)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
