# Generated by Django 3.2.3 on 2021-06-19 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='access',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='climate',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='surveillance',
        ),
        migrations.AddField(
            model_name='storage',
            name='access_24h',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='any_rental_period',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='clever_lock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='inshurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='inventoty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='mobile_app',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='online_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='storage_type',
            field=models.CharField(choices=[('cloud', 'Облачное хранение'), ('individual', 'Индивидуальное хранение'), ('responsibility', 'Ответственное хранение'), ('private', 'Частные кладовки')], default='w', max_length=14),
        ),
        migrations.AddField(
            model_name='storage',
            name='straight_way',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='ventilation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='video_surveillance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storage',
            name='warehouse_type',
            field=models.CharField(choices=[('warm', 'Теплый склад'), ('cold', 'Холодный склад'), ('sea', 'Морской контейнер'), ('box', 'Индивидуальный бокс (умный замок)'), ('zshk', 'Кладовки в ЖК'), ('free', 'Свободные помещения')], default='w', max_length=4),
        ),
        migrations.AddField(
            model_name='storage',
            name='wrapping',
            field=models.BooleanField(default=False),
        ),
    ]
