# Generated by Django 3.2.3 on 2021-06-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='access',
            field=models.CharField(blank=True, choices=[('24h', 'around clock'), ('ttt', 'from time to time')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='climate',
            field=models.CharField(blank=True, choices=[('c', 'cold'), ('w', 'warm')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='square',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='surveillance',
            field=models.CharField(blank=True, choices=[('v', 'video'), ('h', 'human'), ('n', 'none')], max_length=10, null=True),
        ),
    ]
