# Generated by Django 3.2.3 on 2021-06-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0002_auto_20210619_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='storage_type',
            field=models.CharField(blank=True, choices=[('cloud', 'Облачное хранение'), ('individual', 'Индивидуальное хранение'), ('responsibility', 'Ответственное хранение'), ('private', 'Частные кладовки')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='warehouse_type',
            field=models.CharField(choices=[('warm', 'Теплый склад'), ('cold', 'Холодный склад'), ('sea', 'Морской контейнер'), ('box', 'Индивидуальный бокс (умный замок)'), ('zshk', 'Кладовки в ЖК'), ('free', 'Свободные помещения')], default='warm', max_length=4),
        ),
    ]
