# Generated by Django 3.2.3 on 2021-06-12 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0002_alter_storage_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='owner',
            new_name='company_owner',
        ),
    ]
