# Generated by Django 3.2.3 on 2021-06-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0003_rename_owner_storage_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='access',
            field=models.CharField(choices=[('24h', 'around clock'), ('ttt', 'from time to time')], default='ttt', max_length=30),
        ),
        migrations.AlterField(
            model_name='storage',
            name='climate',
            field=models.CharField(choices=[('c', 'cold'), ('w', 'warm')], default='w', max_length=4),
        ),
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='square',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='surveillance',
            field=models.CharField(choices=[('v', 'video'), ('h', 'human'), ('n', 'none')], default='n', max_length=10),
        ),
        migrations.AlterField(
            model_name='storage',
            name='work_hours_end',
            field=models.TimeField(default='23:59:59'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='work_hours_start',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
