# Generated by Django 3.2.3 on 2021-06-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0003_rename_owner_storage_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='access',
            field=models.CharField(choices=[('24h', 'around clock'), ('ttt', 'from time to time')], default='24h', max_length=30),
        ),
        migrations.AlterField(
            model_name='storage',
            name='work_hours_end',
            field=models.TimeField(default='23:59:59'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='work_hours_start',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
