# Generated by Django 3.2.3 on 2021-06-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0003_auto_20210619_0009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='inventoty',
            new_name='inventory',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='storage_type',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='warehouse_type',
        ),
    ]
