# Generated by Django 3.2.3 on 2021-06-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0004_auto_20210616_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='climate',
            field=models.CharField(choices=[('c', 'cold'), ('w', 'warm')], default='w', max_length=4),
        ),
        migrations.AlterField(
            model_name='storage',
            name='surveillance',
            field=models.CharField(choices=[('v', 'video'), ('h', 'human'), ('n', 'none')], default='n', max_length=10),
        ),
    ]
