# Generated by Django 3.2.3 on 2021-06-21 15:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0004_auto_20210621_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='storage_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cloud', 'Облачное хранение'), ('individual', 'Индивидуальное хранение'), ('responsibility', 'Ответственное хранение'), ('private', 'Частные кладовки')], default='warm', max_length=39),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='warehouse_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('warm', 'Теплый склад'), ('cold', 'Холодный склад'), ('sea', 'Морской контейнер'), ('box', 'Индивидуальный бокс (умный замок)'), ('zshk', 'Кладовки в ЖК'), ('free', 'Свободные помещения')], default='cloud', max_length=27),
            preserve_default=False,
        ),
    ]
