# Generated by Django 3.2.3 on 2021-06-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0005_auto_20210616_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='price',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='square',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
