# Generated by Django 3.2.3 on 2021-06-21 19:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0005_auto_20210621_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='storage_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cloud', 'Облачное хранение'), ('individual', 'Индивидуальное хранение'), ('responsibility', 'Ответственное хранение'), ('private', 'Частные кладовки')], max_length=39, null=True),
        ),
        migrations.AlterField(
            model_name='storage',
            name='warehouse_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('warm', 'Теплый склад'), ('cold', 'Холодный склад'), ('sea', 'Морской контейнер'), ('box', 'Индивидуальный бокс (умный замок)'), ('zshk', 'Кладовки в ЖК'), ('free', 'Свободные помещения')], max_length=27, null=True),
        ),
    ]
