# Generated by Django 3.2.3 on 2021-06-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0006_auto_20210621_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='metro',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
