# Generated by Django 3.2.3 on 2021-06-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0007_storage_metro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='metro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
