# Generated by Django 3.2.3 on 2021-06-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '__first__'),
        ('storages', '0008_alter_storage_metro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='metro',
        ),
        migrations.AddField(
            model_name='storage',
            name='metro',
            field=models.ManyToManyField(to='metro.Station'),
        ),
    ]
