# Generated by Django 3.2.3 on 2021-07-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0009_auto_20210629_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
