# Generated by Django 3.2.3 on 2021-07-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0010_auto_20210703_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='status',
            field=models.CharField(choices=[('a', 'accepted'), ('d', 'declined'), ('p', 'in process'), ('m', 'on moderation')], default='on moderation', max_length=20),
        ),
    ]
