# Generated by Django 3.2.3 on 2021-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0011_storage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='status',
            field=models.CharField(choices=[('a', 'accepted'), ('d', 'declined'), ('p', 'in process'), ('m', 'on moderation')], default='m', max_length=20),
        ),
    ]
