# Generated by Django 3.2.3 on 2021-08-01 21:44

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0012_alter_storage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
