# Generated by Django 3.2.3 on 2021-08-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0013_storage_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='storage',
            name='longitude',
        ),
    ]
