# Generated by Django 3.2.3 on 2021-08-22 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0014_auto_20210810_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='storage',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='ok',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 16 digits allowed.", regex='^\\+?\\d{9,16}$')]),
        ),
        migrations.AddField(
            model_name='storage',
            name='vk',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
