# Generated by Django 3.2.3 on 2021-08-27 22:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0015_auto_20210822_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telegram_id', models.CharField(max_length=9)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='storages.storage')),
            ],
        ),
    ]
