# Generated by Django 3.2.3 on 2021-08-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0017_rename_square_storage_max_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='min_square',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
