# Generated by Django 3.2.3 on 2021-08-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0018_storage_min_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='promo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
