# Generated by Django 3.2.3 on 2021-09-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0019_storage_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='status',
            field=models.CharField(choices=[('a', 'accepted'), ('d', 'declined'), ('p', 'in process'), ('m', 'on moderation')], default='a', max_length=20),
        ),
    ]
