# Generated by Django 3.2.3 on 2021-06-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='category',
            field=models.CharField(choices=[('s', 'storage'), ('c', 'company')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
