# Generated by Django 3.2.3 on 2021-06-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_is_private'),
        ('authentication', '0002_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='companies',
            field=models.ManyToManyField(to='company.Company'),
        ),
    ]
