# Generated by Django 3.2.3 on 2021-06-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
