# Generated by Django 3.2.3 on 2021-09-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metro', '0004_alter_station_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='code_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
