# Generated by Django 3.2.3 on 2021-06-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storages', '0002_auto_20210604_1950'),
        ('company', '0002_company_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='storages',
            field=models.ManyToManyField(to='storages.Storage'),
        ),
    ]
