# Generated by Django 3.2.3 on 2021-06-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_company_owner'),
        ('storages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='storages',
            field=models.ManyToManyField(to='storages.Storage'),
        ),
    ]
