# Generated by Django 3.2.3 on 2021-06-20 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
