# Generated by Django 3.2.3 on 2021-06-12 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_storages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='storages',
        ),
    ]
