# Generated by Django 3.2.3 on 2021-10-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_company_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('a', 'accepted'), ('d', 'declined'), ('m', 'on moderation')], default='m', max_length=20),
        ),
    ]
