# Generated by Django 3.2.3 on 2021-06-15 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('company', '0004_remove_company_storages'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='images.image'),
            preserve_default=False,
        ),
    ]
